//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticalPerCategoryTable
    {
        public int Id { get; set; }
        public int CatId { get; set; }
        public int ArtId { get; set; }
        public int Points { get; set; }
    
        public virtual ArticalTable ArticalTable { get; set; }
        public virtual CategoryTable CategoryTable { get; set; }
    }
}
