//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryTable()
        {
            this.ArticalPerCategoryTables = new HashSet<ArticalPerCategoryTable>();
            this.CategoryTable1 = new HashSet<CategoryTable>();
            this.WordPerCategoryTables = new HashSet<WordPerCategoryTable>();
        }
    
        public int Id { get; set; }
        public string Kod { get; set; }
        public string Desciption { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int AmountArticals { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticalPerCategoryTable> ArticalPerCategoryTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryTable> CategoryTable1 { get; set; }
        public virtual CategoryTable CategoryTable2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WordPerCategoryTable> WordPerCategoryTables { get; set; }
    }
}
