//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shortSortDBEntities : DbContext
    {
        public shortSortDBEntities()
            : base("name=shortSortDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArticalPerCategoryTable> ArticalPerCategoryTables { get; set; }
        public virtual DbSet<ArticalTable> ArticalTables { get; set; }
        public virtual DbSet<CategoryTable> CategoryTables { get; set; }
        public virtual DbSet<PermissionTable> PermissionTables { get; set; }
        public virtual DbSet<SimilarWordTable> SimilarWordTables { get; set; }
        public virtual DbSet<WordPerCategoryTable> WordPerCategoryTables { get; set; }
    }
}
