//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordPerCategoryTable
    {
        public int Id { get; set; }
        public string Word { get; set; }
        public int CatId { get; set; }
        public int Amount { get; set; }
    
        public virtual CategoryTable CategoryTable { get; set; }
    }
}
